POST http://localhost:8000/user/register
Content-Type: application/json

{
    "first_name": "Axelio",
    "last_name": "HaBaPoB",
    "email": "kukuladze113@mail.ru",
    "password": "12345agjhgdugsi",
    "company": "Xga3npoM",
    "position": "Dolgnostr"
}

###

POST http://localhost:8000/user/register
Content-Type: application/json

{
    "first_name": "Arxeelio",
    "last_name": "HarBaePoB",
    "email": "alex12mb@mail.ru",
    "password": "12345argjhgdugsi",
    "company": "Xgra3npoM",
    "position": "Dolrgnostr"
}

###
POST http://localhost:8000/user/register
Content-Type: application/json

{
    "first_name": "Hukojiau",
    "last_name": "Cobolev",
    "email": "majixim2@mail.ru",
    "password": "12345agjhgdugsi",
    "company": "X3company",
    "position": "Manager",
    "type": "shop"
}

###

POST http://localhost:8000/user/register/confirm
Content-Type: application/json

{
    "email": "kukuladze113@mail.ru",
    "token": "509af28e234cbe26bd574f9c89ae18f3229e1"
}

###


POST http://localhost:8000/user/register/confirm
Content-Type: application/json

{
    "email": "alex12mb@mail.ru",
    "token": "bfbc0360a1105c99ae758e6bf7c835a18"
}

###

POST http://localhost:8000/user/register/confirm
Content-Type: application/json

{
    "email": "majixim2@mail.ru",
    "token": "4ae48e5a403966385891e803"
}

###

POST http://localhost:8000/user/login
Content-Type: application/json

{
    "email": "pbk2007@inbox.ru",
    "password": "12345agjhgdugsi"
}

###
POST http://localhost:8000/user/passwordreset
Content-Type: application/json

{
    "email": "kukuladze113@mail.ru"
}

###

GET http://localhost:8000/user/details

###

POST http://localhost:8000/user/details
Content-Type: application/json

{
    "password": "12345agjhgdugsi",
    "company": "X8"
}

###
GET http://localhost:8000/user/contact
Authorization: Token b2395b613c581c322a833c9ff8661cbf8d248a70

###
GET http://localhost:8000/user/contacts

###

POST http://localhost:8000/user/contacts
Content-Type: application/json

{
    "city": "Msk",
    "street": "Lenina",
    "house": "91",
    "structure": "1",
    "building": "A",
    "apartment": "13",
    "phone": "90000",
    "user": 7
}

###

PUT http://localhost:8000/user/contact
Content-Type: application/json

{
    "city": "SPB",
    "street": "Nevskiy",
    "house": "90",
    "structure": "2",
    "building": "B",
    "apartment": "13",
    "phone": "90000",
    "id": 4
}

###

DELETE http://localhost:8000/user/contact
Content-Type: application/json

{
    "items": "4"
}

###

GET http://localhost:8000/shops

###

POST http://localhost:8000/shops
Content-Type: application/json

{
    "name": "Shop_test",
    "url": null,
    "state": true,
    "user": 7
}

###

GET http://localhost:8000/categories

###

POST http://localhost:8000/categories
Content-Type: application/json

{
    "name": "Flash-накопители",
    "shops": [4]
}

###

GET http://localhost:8000/products?shop_id=4&category_id=4

###

GET http://localhost:8000/partner/state

###

POST http://localhost:8000/partner/state
Content-Type: application/json

{
    "state": "on"
}

###
POST http://localhost:8000/partner/update
Content-Type: application/json
Authorization: Token b2395b613c581c322a833c9ff8661cbf8d248a70

{
    "url": "https://raw.githubusercontent.com/netology-code/pd-diplom/master/data/shop1.yaml"
}

###
POST http://localhost:8000/cart
Content-Type: application/x-www-form-urlencoded
Authorization: Token b2395b613c581c322a833c9ff8661cbf8d248a70


"items": [ { "external_id": 4, "quantity": 13 } ]



###
GET http://localhost:8000/cart
Authorization: Token b2395b613c581c322a833c9ff8661cbf8d248a70

###
PUT http://localhost:8000/cart
Content-Type: application/x-www-form-urlencoded
Authorization: Token b2395b613c581c322a833c9ff8661cbf8d248a70


"items": [ {"id": 1, "quantity": 12} ]


### 
DELETE http://localhost:8000/cart
Content-Type: application/x-www-form-urlencoded
Authorization: Token b2395b613c581c322a833c9ff8661cbf8d248a70


"items": 2


###
POST http://localhost:8000/order
Content-Type: application/x-www-form-urlencoded
Authorization: Token b2395b613c581c322a833c9ff8661cbf8d248a70


"id": 1,
"contact": 5

###
GET http://localhost:8000/order
Authorization: Token b2395b613c581c322a833c9ff8661cbf8d248a70

###
GET http://localhost:8000/partner/orders
Authorization: Token b2395b613c581c322a833c9ff8661cbf8d248a70
